version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Debug
- Release
before_build:
build:
  project: NuttyPutters/NuttyPutters.vcxproj
  parallel: true
  verbosity: minimal
artifacts:
- path: x64/Debug$(configuration)/NuttyPutters.exe